### PR TITLE
State unmaintained status

### PR DESCRIPTION
**Pull request by ssbarnea**
As this project had CI broken for very long time, PRs without reviews, issue tracker disabled and no other issue tracker advertised on its readme, we can only assume is dead, unless someones wants to takeover its maintenance.

### CODE REVIEW

**Comment by rbtcollins** [comment]
I have added more maintainers some time ago, and Jelmer did a release on March 14.

and as far as the issue tracker is concerned, the metadata in setup.py points to launchpad, where the bug tracker for it is. Though certainly, we could move it here, if someone wanted to volunteer the effort. https://github.com/testing-cabal/subunit/blob/master/setup.py#L69

I don't think calling this unmaintained is correct, or appropriate.

**Comment by ssbarnea** [comment]
Yes, moving the issue tracker from LP, would indeed be a very good move.

I am aware of basic issues that were runtime warnings for a very long time like:
```
.tox/cover/lib/python3.8/site-packages/subunit/__init__.py:1036
  /Users/ssbarnea/c/opendev/elastic-recheck/.tox/cover/lib/python3.8/site-packages/subunit/__init__.py:1036: DeprecationWarning: invalid escape sequence \d
    match = re.match("(\d+)\.\.(\d+)\s*(?:\#\s+(.*))?\n", line)

.tox/cover/lib/python3.8/site-packages/subunit/__init__.py:1049
  /Users/ssbarnea/c/opendev/elastic-recheck/.tox/cover/lib/python3.8/site-packages/subunit/__init__.py:1049: DeprecationWarning: invalid escape sequence \s
    match = re.match("(ok|not ok)(?:\s+(\d+)?)?(?:\s+([^#]*[^#\s]+)\s*)?(?:\s+#\s+(TODO|SKIP|skip|todo)(?:\s+(.*))?)?\n", line)

.tox/cover/lib/python3.8/site-packages/subunit/__init__.py:1077
  /Users/ssbarnea/c/opendev/elastic-recheck/.tox/cover/lib/python3.8/site-packages/subunit/__init__.py:1077: DeprecationWarning: invalid escape sequence \!
    match = re.match("Bail out\!(?:\s*(.*))?\n", line)

.tox/cover/lib/python3.8/site-packages/subunit/__init__.py:1089
  /Users/ssbarnea/c/opendev/elastic-recheck/.tox/cover/lib/python3.8/site-packages/subunit/__init__.py:1089: DeprecationWarning: invalid escape sequence \#
    match = re.match("\#.*\n", line)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

These are syntax errors with newer python versions, and easy to spot and fix, if CI would be green.

AFAIK, broken CI for months equals to unmaintained and I do not expect occasional contributors to fix CI too, even if that is theoretically possible.

**Comment by rbtcollins** [comment]
Python has changed behaviour on showing DeprecationWarnings to users by default, but these are not functional issues with the code (the escapes are preserved and thus honoured by re), nor reflective of actual bugs, though yes, it would be good to fix them now that they are visible. It would have been nicer to get a patch rather than a omg-its-not-supported thing. Saying its an issue for a long time is a stretch - few folk have been using Python 3.8, though uptake is growing. Anyhow, yes, sure, lets fix it.

**Comment by ssbarnea** [comment]
@rbtcollins I am happy to raise a PR to address these but travis will still report red due to broken 3.4 job.

**Comment by rbtcollins** [comment]
3.4 is EOL so we should remove it from the matrix at this point.

**Pull request closed without merging**
